name:                TypelevelReflection
version:             0.1.0.0
github:              "githubuser/TypelevelReflection"
license:             Apache-2.0
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2020 Thomas Mahler"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Using haskell typelevel programming to implement reflective features.
# category:            Programming

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TypelevelReflection#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- aeson
- vector

library:
  source-dirs: src

executables:
  TypelevelReflection-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TypelevelReflection

tests:
  TypelevelReflection-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TypelevelReflection
